version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: shopkeepr-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: .
    container_name: shopkeepr-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:Chewy0216!@db:5432/shopkeeprDatabase
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine
    container_name: shopkeepr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopkeeprDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chewy0216!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: shopkeepr-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
